In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/Titanic-Dataset.csv

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
df = pd.read_csv('/kaggle/input/titanic/Titanic-Dataset.csv')
knn = KNeighborsClassifier(n_neighbors=1)
d=df.loc[:,:].dropna()

d.Survived = d.Survived.map({0:'S',1:'N'})
d.Sex = d.Sex.map({'female':0,'male':1})
d.Embarked = d.Embarked.map({'S':1,'C':0})

x=d[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare']].values
y = d.Survived.values
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42)
x=x
knn.fit(x_train,y_train)

pred = knn.predict(x_test)
pred

array(['N', 'S', 'N', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'S', 'N', 'N',
       'N', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'S', 'N', 'N',
       'N', 'S', 'S', 'N', 'N', 'S', 'N', 'N', 'N', 'S', 'S', 'N', 'N',
       'S', 'N', 'S', 'N', 'N', 'S', 'N'], dtype=object)

In [3]:
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,N,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,0.0
3,4,N,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,1.0
6,7,S,1,"McCarthy, Mr. Timothy J",1,54.0,0,0,17463,51.8625,E46,1.0
10,11,N,3,"Sandstrom, Miss. Marguerite Rut",0,4.0,1,1,PP 9549,16.7000,G6,1.0
11,12,N,1,"Bonnell, Miss. Elizabeth",0,58.0,0,0,113783,26.5500,C103,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,N,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",0,47.0,1,1,11751,52.5542,D35,1.0
872,873,S,1,"Carlsson, Mr. Frans Olof",1,33.0,0,0,695,5.0000,B51 B53 B55,1.0
879,880,N,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",0,56.0,0,1,11767,83.1583,C50,0.0
887,888,N,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,1.0
889,890,N,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,0.0

In [4]:
#test small predict 

data = [[3,2,0,24,0,1,72.657]]
pred = knn.predict(data)
pred

array(['N'], dtype=object)